version: '3'

services:
  # Node.js application service
  item-app:
    image: sanjanivicky/item-app:v1  # Specify the Docker image for the Node.js application
    ports:
      - "80:8080"  # Map port 80 on the host to port 8080 on the container
    restart: always  # Apply the "always" restart policy
    
  # MongoDB service
  item-db:
    image: mongo:3  # Specify the Docker image for MongoDB
    volumes:
      - app-db:/data/db  # Mount a volume for MongoDB data
    restart: always  # Apply the "always" restart policy

# Define a named volume for MongoDB data
volumes:
  app-db:
