version: "3.4"
services:
  consumer:
    image: sanjanivicky/shipping-service:v1
    volumes:
      - .:/src
    environment:
      NODE_ENV: production
      AMQP_URL: amqp://localhost:5673
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    external:
      name: rabbitmq_default
